apiVersion: v1
kind: Service
metadata:
  name: lockers-svc
  namespace: veerabank
spec:
  type: ClusterIP
  selector:
    app: lockers
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
